<template>
  <div class="record-viewing-view">
    <h2>记录查看</h2>
    <!-- 记录查看页面标题 -->
    <!-- Record Viewing Page Title -->

    <!-- 筛选区域 (占位) -->
    <!-- Filter Area (Placeholder) -->
    <el-form :inline="true" :model="filters" class="filter-bar">
      <el-form-item label="设备SN">
        <!-- 设备SN输入框 -->
        <!-- Device SN Input -->
        <el-input v-model="filters.deviceSN" placeholder="请输入设备SN"></el-input>
      </el-form-item>
      <el-form-item label="日期范围">
        <!-- 日期范围选择器 -->
        <!-- Date Range Picker -->
        <el-date-picker
          v-model="filters.dateRange"
          type="daterange"
          range-separator="至"
          start-placeholder="开始日期"
          end-placeholder="结束日期">
        </el-date-picker>
      </el-form-item>
      <el-form-item>
        <!-- 查询按钮 -->
        <!-- Query Button -->
        <el-button type="primary" @click="handleFilter">查询</el-button>
      </el-form-item>
    </el-form>

    <el-tabs v-model="activeTabName" class="record-tabs">
      <!-- Element Plus 标签页 -->
      <!-- Element Plus Tabs -->
      <el-tab-pane label="识别记录" name="identification">
        <!-- 识别记录标签页 -->
        <!-- Identification Records Tab -->
        <el-table :data="identificationRecords" style="width: 100%" border stripe>
          <!-- 识别记录表格 -->
          <!-- Identification Records Table -->
          <el-table-column prop="deviceSN" label="设备SN" width="180" />
          <el-table-column prop="recordID" label="记录ID" width="100" />
          <el-table-column prop="recordType" label="事件类型" width="150">
            <!-- 事件类型，使用格式化函数 -->
            <!-- Event Type, uses formatting function -->
            <template #default="scope">{{ formatIdentificationRecordType(scope.row.recordType) }}</template>
          </el-table-column>
          <el-table-column prop="userID" label="用户ID" width="100" />
          <el-table-column prop="name" label="姓名" width="120" />
          <el-table-column prop="cardNum" label="卡号" width="120" />
          <el-table-column prop="bodyTemp" label="体温 (°C)" width="100" />
          <el-table-column prop="recordDate" label="打卡时间" width="180" />
          <el-table-column label="照片" width="80" align="center">
            <!-- 照片查看按钮 -->
            <!-- View Photo Button -->
            <template #default="scope">
              <el-button v-if="scope.row.hasPhoto" size="small" @click="viewRecordPhoto(scope.row)">查看</el-button>
            </template>
          </el-table-column>
        </el-table>
      </el-tab-pane>

      <el-tab-pane label="系统记录" name="system">
        <!-- 系统记录标签页 -->
        <!-- System Records Tab -->
        <el-table :data="systemRecords" style="width: 100%" border stripe>
          <!-- 系统记录表格 -->
          <!-- System Records Table -->
          <el-table-column prop="deviceSN" label="设备SN" width="180" />
          <el-table-column prop="recordID" label="记录ID" width="100" />
          <el-table-column prop="outerRecordType" label="主类型" width="120">
            <!-- 主类型，使用格式化函数 -->
            <!-- Outer Record Type, uses formatting function -->
            <template #default="scope">{{ formatOuterSystemRecordType(scope.row.outerRecordType) }}</template>
          </el-table-column>
          <el-table-column prop="eventSpecificType" label="事件类型" width="200">
            <!-- 具体事件类型，使用格式化函数 -->
            <!-- Specific Event Type, uses formatting function -->
            <template #default="scope">{{ formatSpecificSystemRecordType(scope.row.outerRecordType, scope.row.eventSpecificType) }}</template>
          </el-table-column>
          <el-table-column prop="recordDate" label="发生时间" width="180" />
        </el-table>
      </el-tab-pane>
    </el-tabs>
    <!-- TODO: 照片查看弹窗 -->
    <!-- Placeholder for future Photo Viewing Dialog -->
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, reactive } from 'vue';
// 按需导入Element Plus组件 (Import Element Plus components on demand)
import { ElTabs, ElTabPane, ElTable, ElTableColumn, ElButton, ElForm, ElFormItem, ElInput, ElDatePicker } from 'element-plus';

// 识别记录接口定义
// Interface definition for IdentificationRecord
interface IdentificationRecord {
  id: string; // 唯一标识 (Unique identifier)
  deviceSN: string; // 设备序列号 (Device serial number)
  recordID: number; // 设备生成的记录ID (Record ID generated by device)
  recordType: number; // 记录类型 (Record type - e.g., face, card, etc.)
  userID?: string; // 用户ID (User ID - optional)
  name?: string; // 姓名 (Name - optional)
  cardNum?: string; // 卡号 (Card number - optional)
  bodyTemp?: number; // 体温 (Body temperature - optional)
  recordDate: string; // 记录时间 (字符串格式，方便显示) (Record time - string format for easy display)
  hasPhoto?: boolean; // 是否有照片 (Whether there is a photo - optional)
  photoUrl?: string; // 照片URL (Photo URL - optional)
}

// 系统记录接口定义
// Interface definition for SystemRecord
interface SystemRecord {
  id: string; // 唯一标识 (Unique identifier)
  deviceSN: string; // 设备序列号 (Device serial number)
  recordID: number; // 设备生成的记录ID (Record ID generated by device)
  outerRecordType: number; // 记录主类型 (1: 门磁记录, 2: 系统记录) (Main record type: 1 for door magnetic, 2 for system)
  eventSpecificType: number; // 具体事件类型代码 (Specific event type code)
  recordDate: string; // 记录时间 (字符串格式，方便显示) (Record time - string format for easy display)
}

export default defineComponent({
  name: 'RecordViewingView', // 组件名称 (Component name)
  components: {
    // 注册按需导入的 Element Plus 组件
    // Register on-demand imported Element Plus components
    ElTabs, ElTabPane, ElTable, ElTableColumn, ElButton, ElForm, ElFormItem, ElInput, ElDatePicker
  },
  setup() {
    // Vue 3 Composition API setup function

    const activeTabName = ref('identification'); // 默认激活的Tab名称 (Name of the default active tab)
    
    // 筛选表单的响应式数据模型
    // Reactive data model for the filter form
    const filters = reactive({
      deviceSN: '', // 设备SN筛选条件 (Device SN filter condition)
      dateRange: null as [Date, Date] | null, // 日期范围筛选条件 (Date range filter condition)
    });

    // 模拟识别记录数据
    // Simulate identification records data
    const identificationRecords = ref<IdentificationRecord[]>([
      { id: 'ir1', deviceSN: 'FC-8200H12345678', recordID: 120, recordType: 3, userID: '1001', name: '张三', cardNum: '88881001', bodyTemp: 36.5, recordDate: new Date().toLocaleString(), hasPhoto: true, photoUrl: 'sample_photo_1.jpg' },
      { id: 'ir2', deviceSN: 'FC-8200HABCDEFGH', recordID: 121, recordType: 1, userID: '1002', name: '李四', cardNum: '88881002', recordDate: new Date(Date.now() - 3600000).toLocaleString(), hasPhoto: false },
      { id: 'ir3', deviceSN: 'FC-8300T98765432', recordID: 122, recordType: 19, userID: 'N/A', name: '陌生人', cardNum: 'N/A', recordDate: new Date(Date.now() - 7200000).toLocaleString(), hasPhoto: true, photoUrl: 'sample_photo_stranger.jpg' },
    ]);

    // 模拟系统记录数据
    // Simulate system records data
    const systemRecords = ref<SystemRecord[]>([
      { id: 'sr1', deviceSN: 'FC-8200H12345678', recordID: 1, outerRecordType: 1, eventSpecificType: 1, recordDate: new Date().toLocaleString() }, // 门磁-开门 (Door magnetic - Door open)
      { id: 'sr2', deviceSN: 'FC-8200H12345678', recordID: 2, outerRecordType: 2, eventSpecificType: 14, recordDate: new Date(Date.now() - 7200000).toLocaleString() }, // 系统-非法认证报警 (System - Illegal authentication alarm)
      { id: 'sr3', deviceSN: 'FC-8300T98765432', recordID: 3, outerRecordType: 1, eventSpecificType: 5, recordDate: new Date(Date.now() - 10800000).toLocaleString() }, // 门磁-门未关好 (Door magnetic - Door not closed properly)
      { id: 'sr4', deviceSN: 'FC-8200HABCDEFGH', recordID: 4, outerRecordType: 2, eventSpecificType: 28, recordDate: new Date(Date.now() - 14400000).toLocaleString() }, // 系统-系统加电 (System - System power on)
    ]);

    // TODO: 在后续步骤中，将替换为从API获取数据的逻辑
    // In subsequent steps, this will be replaced with logic to fetch data from the API
    // onMounted(async () => { /* ... API calls ... */ });

    // 格式化识别记录事件类型
    // Format identification record event type
    const formatIdentificationRecordType = (type: number): string => {
      // 这些类型应与后端API文档中的 "RecordType 事件类型" 定义相对应
      // These types should correspond to the "RecordType Event Types" definition in the backend API documentation
      const types: { [key: number]: string } = {
        0: '刷卡 (Card Swipe)', 1: '指纹 (Fingerprint)', 2: '人脸 (Face)', 3: '密码 (Password)',
        4: '二维码 (QR Code)', 5: '多重验证 (Multi-Factor)', 6: '手动输入 (Manual Input)',
        7: '远程开门 (Remote Open)', 8: '按钮开门 (Button Open)', 9: '出门开关 (Exit Button)',
        10: '胁迫报警 (Duress Alarm)', 11: '陌生人 (Stranger)', 12: '黑名单 (Blacklist)',
        13: '卡号不存在 (Card Not Exist)', 14: '有效期错误 (Invalid Period)', 15: '时段错误 (Time Slot Error)',
        16: '节假日错误 (Holiday Error)', 17: '次数用尽 (Times Used Up)',
        18: '体温异常 (Abnormal Temperature)', 19: '未戴口罩 (No Mask)'
      };
      return types[type] || `未知类型 (${type})`; // Unknown type
    };

    // 格式化系统记录主类型
    // Format outer system record type
    const formatOuterSystemRecordType = (type: number): string => {
      return type === 1 ? '门磁记录 (Door)' : type === 2 ? '系统记录 (System)' : `未知 (${type})`; // Unknown
    };

    // 格式化具体系统记录事件类型
    // Format specific system record event type
    const formatSpecificSystemRecordType = (outerType: number, specificType: number): string => {
      // 这些类型应与后端API文档中的 "门磁记录 事件类型" 和 "系统记录 事件类型" 定义相对应
      // These types should correspond to the "Door Magnetic Record Event Types" and "System Record Event Types" in the backend API documentation
      if (outerType === 1) { // 门磁记录 (Door Magnetic Records)
        const types: { [key: number]: string } = {
          0: '门磁关 (Door Close)', 1: '门磁开 (Door Open)', 2: '按钮开门 (Button Open)', 3: '胁迫开门 (Duress Open)',
          4: '远程开门 (Remote Open)', 5: '出门开关开门 (Exit Button Open)', 6: '常开状态 (Keep Open)',
          7: '常关状态 (Keep Close)', 8: '门未关报警 (Door Ajar Alarm)', 9: '门被意外打开报警 (Door Forced Open Alarm)',
          10: '胁迫报警 (Duress Alarm)', 11: '防拆报警 (Tamper Alarm)', 12: '火警报警 (Fire Alarm)',
          13: '烟感报警 (Smoke Alarm)', 14: '匪警报警 (Panic Alarm)', 15: '紧急按钮报警 (Emergency Button Alarm)',
          16: '其他报警 (Other Alarm)'
        };
        return types[specificType] || `未知门磁事件 (${specificType})`; // Unknown door magnetic event
      } else if (outerType === 2) { // 系统记录 (System Records)
        const types: { [key: number]: string } = {
          0: '设备上电 (Device Power On)', 1: '设备重启 (Device Reboot)', 2: '设备参数修改 (Params Modified)',
          3: '设备时间修改 (Time Modified)', 4: '恢复出厂设置 (Factory Reset)', 5: '固件升级 (Firmware Upgrade)',
          6: '数据清除 (Data Cleared)', 7: 'NTP校时 (NTP Sync)', 8: 'HTTP连接成功 (HTTP Connected)',
          9: 'HTTP连接失败 (HTTP Connect Fail)', 10: 'MQTT连接成功 (MQTT Connected)',
          11: 'MQTT连接失败 (MQTT Connect Fail)', 12: '网络断开 (Network Disconnected)',
          13: '网络连接成功 (Network Connected)', 14: 'TF卡满 (TF Card Full)',
          15: 'TF卡异常 (TF Card Error)', 16: 'RTC异常 (RTC Error)'
        };
        return types[specificType] || `未知系统事件 (${specificType})`; // Unknown system event
      }
      return `未知 (${specificType})`; // Unknown
    };

    // 查看照片 (占位逻辑)
    // View photo (placeholder logic)
    const viewRecordPhoto = (record: IdentificationRecord) => {
      console.log('查看记录照片 (View Record Photo):', record.id, record.photoUrl || '无URL (No URL)');
      // TODO: 实现照片查看逻辑 (例如弹窗显示图片，需要一个照片查看组件或对话框)
      // Implement photo viewing logic (e.g., display image in a dialog, requires a photo viewer component or dialog)
      alert(`模拟查看照片 (Simulate viewing photo for record ID): ${record.id}. 照片URL (Photo URL): ${record.photoUrl || 'N/A'}`);
    };

    // 处理筛选 (占位逻辑)
    // Handle filter (placeholder logic)
    const handleFilter = () => {
      console.log('应用筛选条件 (Applying filter conditions):', JSON.parse(JSON.stringify(filters)));
      // TODO: 实现基于筛选条件的API请求逻辑，并更新表格数据
      // Implement API request logic based on filter conditions and update table data
      alert(`模拟查询，条件 (Simulate query with conditions):\n设备SN (Device SN): ${filters.deviceSN}\n日期范围 (Date Range): ${filters.dateRange ? filters.dateRange.map(d=>d.toLocaleDateString()).join(' - ') : 'N/A'}`);
    };

    // 返回组件模板所需的数据和方法
    // Return data and methods needed by the component template
    return {
      activeTabName,
      filters,
      identificationRecords,
      systemRecords,
      formatIdentificationRecordType,
      formatOuterSystemRecordType,
      formatSpecificSystemRecordType,
      viewRecordPhoto,
      handleFilter,
    };
  },
});
</script>

<style scoped>
.record-viewing-view {
  padding: 20px; /* 视图内边距 (Padding for the view) */
}
.filter-bar {
  margin-bottom: 20px; /* 筛选条下边距 (Bottom margin for filter bar) */
  padding: 15px; /* 筛选条内边距 (Padding for filter bar) */
  background-color: #f9f9f9; /* 筛选条背景色 (Background color for filter bar) */
  border-radius: 4px; /* 筛选条圆角 (Border radius for filter bar) */
}
.record-tabs {
  margin-top: 10px; /* Tab区域上边距 (Top margin for tabs area) */
}
/* 可以添加更多自定义样式 */
/* More custom styles can be added here */
</style>
